version: "3.8"

services:
    api:
        image: yigal14/hospital_api:latest
        build:
            context: .
            dockerfile: HospitalWeb.WebApi/Dockerfile
        container_name: hospital-api
        ports:
            - "7080:80"
            - "7443:443"
        environment:
            AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
            AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
            AZURE_KEY_VAULT: ${AZURE_KEY_VAULT}
            AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    
    mvc:
        image: yigal14/hospital_mvc:latest
        build:
            context: .
            dockerfile: HospitalWeb.Mvc/Dockerfile
        container_name: hospital-mvc
        ports:
            - "8080:80"
            - "8443:443"
        environment:
            AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
            AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
            AZURE_KEY_VAULT: ${AZURE_KEY_VAULT}
            AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    