name: Docker compose CD

on:
  push:
    branches: [ "Develope" ]
  pull_request:
    branches: [ "Develope" ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker-compose build
      run: docker-compose -f ./HospitalWeb/docker-compose.yml build
    - name: Docker-compose push
      run: docker-compose -f ./HospitalWeb/docker-compose.yml push
